import type { Organisation } from "@/types/organization";

export const organizations: Organisation[] = [
  {
    id: "org_001",
    name: "ADSSE",
    full_name: "Association pour le Développement Social et la Sauvegarde de l'Environnement",
    acronym: "ADSSE",
    logo_url: "/logos/adsse.png",
    founded: 1997,
    founded_date: "15 mai 1997",
    founded_city: "Bukavu",
    founded_province: "Sud-Kivu",
    province_primary: "Ituri",
    city: "Bunia",
    headquarters: "Avenue du Bas-Congo No. 835, Commune de la Gombe, Kinshasa, RD Congo",
    website: "http://www.adsse.org",
    contact_email: "info@adsse.org",
    contact_email_1: "info@adsse.org",
    contact_email_2: "xmayele@adsse.org",
    contact_phone: "+243 815 117 685",
    verified: true,
    status: "active",
    experience_years: 27,
    experience_badge: "Plus de 27 ans d'expérience dans le travail communautaire.",
    provinces_covered: [
      "Ituri",
      "Nord Kivu",
      "Sud Kivu",
      "Kinshasa",
      "Maniema",
      "Tanganyika",
      "Haut-Katanga",
      "Kasaï Central",
      "Kasaï",
      "Haut-Uélé",
      "Nord-Ubangi",
      "Sud-Ubangi",
      "Haut-Lomami",
      "Équateur",
    ],
    sectors: [
      "Abris et Articles Ménagers Essentiels (AME)",
      "Livelihood (Moyens de subsistance)",
      "Nutrition",
      "Eau, Hygiène et Assainissement (EHA/WASH)",
      "Éducation",
    ],
    description: "Créée le 17 mai 1997 à Bukavu, dans la province du Sud-Kivu en République Démocratique du Congo, dans le contexte post-génocide rwandais, l'Association pour le Développement Social et la Sauvegarde de l'Environnement (ADSSE) est une organisation non gouvernementale (ONG) de droit congolais.",
    description_fr:
      "Créée le 17 mai 1997 à Bukavu, dans la province du Sud-Kivu en République Démocratique du Congo, dans le contexte post-génocide rwandais, l'Association pour le Développement Social et la Sauvegarde de l'Environnement (ADSSE) est une organisation non gouvernementale (ONG) de droit congolais.",
    vision: "Contribuer à l'action humanitaire localisée dans le respect de l'environnement, pour une plus grande efficacité et rapidité.",
    mission_fr:
      "Aider la population à identifier ses problèmes et les transformer en projets de développement. Initier des projets pour restaurer l'équilibre environnemental après des catastrophes naturelles ou des guerres. Créer des initiatives pour alléger la corvée des femmes et leur permettre de participer aux activités économiques. Soutenir les victimes de catastrophes naturelles, de violences sexuelles et les populations vulnérables.",
    mission_points: [
      "Aider la population à identifier ses problèmes et les transformer en projets de développement.",
      "Initier des projets pour restaurer l'équilibre environnemental après des catastrophes naturelles ou des guerres.",
      "Créer des initiatives pour alléger la corvée des femmes et leur permettre de participer aux activités économiques.",
      "Soutenir les victimes de catastrophes naturelles, de violences sexuelles et les populations vulnérables (réfugiés, déplacés internes, etc.).",
    ],
    domains: [
      "Activités humanitaires.",
      "Activités de développement : renforcer l'engagement et la résilience au sein de la communauté.",
      "Reboisement, lutte contre la déforestation et le changement climatique.",
    ],
    values: [
      "Prise en compte des 4 principes humanitaires dans les interventions",
      "Transparence & Redevabilité",
      "Protection de l'environnement",
      "Intégrité & lutte contre les abus sexuels",
    ],
    images: [
      "/images/adsse/adsse1.png",
      "/images/adsse/adsse2.png",
      "/images/adsse/adsse3.png",
      "/images/adsse/adsse4.png",
    ],
    map_image: "/images/adsse/adssemap.png",
    partner_logos: Array.from({ length: 11 }, (_, i) => `/images/adsse/partners/logo${i + 1}.png`),
    staff_count: 225,
    offices_count: 19,
    impact_note: "En 27 ans d'existence, ADSSE a assisté 12,780,000 personnes dont : 983,000 réfugiés (8%), 9,628,000 personnes déplacées internes (75%) et 2,169,000 communautés hôtes (17%)",
    team_note: "225 staffs répartis sur 19 bureaux à travers le pays",
    stats: {
      projects_completed: 47,
      people_helped: 12780000,
      partners_count: 11,
      experience_years: 27,
    },
    tags: [
      "Développement communautaire",
      "Protection environnement",
      "Femmes",
      "Réfugiés",
      "Déplacés internes",
    ],
  },
  {
    id: "org_002",
    slug: "aides",
    name: "AIDES",
    full_name: "Actions et Interventions pour le Développement et l'Encadrement Social",
    acronym: "AIDES",
    logo_url: "/logos/aides.png",
    founded: 1998,
    province_primary: "Nord Kivu",
    city: "Goma",
    headquarters: "Siège social à Kinshasa",
    headquarters_city: "Kinshasa",
    contact_email: "contact@aides-drc.org",
    social: {
      twitter: "https://x.com/aides_rdc?s=11",
      facebook: "https://m.facebook.com/aidesgom/",
    },
    verified: true,
    status: "active",
    provinces_covered: [
      "Kinshasa",
      "Nord Kivu",
      "Sud Kivu",
      "Tanganyika",
      "Kasaï",
      "Kasaï Central",
      "Nord Ubangi",
      "Sud Ubangi",
    ],
    operational_offices: [
      "Kinshasa (siège social)",
      "Goma (Nord Kivu)",
      "Beni (Nord Kivu)",
      "Bukavu (Sud Kivu)",
      "Uvira (Sud Kivu)",
      "Baraka (Sud Kivu)",
      "Kalemie (Tanganyika)",
      "Nyunzu (Tanganyika)",
      "Tshikapa (Kasaï)",
      "Kananga (Kasaï Central)",
      "Gbadolite (Nord Ubangi)",
      "Bili (Nord Ubangi)",
      "Yakoma (Nord Ubangi)",
      "Libenge (Sud Ubangi)",
      "Zongo (Sud Ubangi)",
    ],
    sectors: [
      "Protection",
      "Abris & Articles Ménagers Essentiels (AME)",
      "CCCM (Coordination et Gestion des Sites)",
      "Santé",
      "Sécurité Alimentaire",
      "Moyens de subsistance",
    ],
    description_fr:
      "AIDES est une organisation non gouvernementale de droit congolais qui apporte une assistance humanitaire intégrée, impartiale et digne aux victimes des crises humanitaires (réfugiés, personnes déplacées internes, retournés, rapatriés) et autres catastrophes (sinistrés) en répondant à leurs besoins essentiels, en protégeant leurs droits fondamentaux et en renforçant leur autonomie et leur résilience. Ses interventions se sont élargies au fil du temps sur le territoire national où les besoins se font sentir.",
    staff_count: 347,
    offices_count: 15,
    team_note: "347 membres, employés de AIDES de la Direction Générale et des différents projets",
    impact_note: "En 2025, environ 1,456,686 personnes sont assistées à travers 15 projets mis en œuvre dans les secteurs de santé, éducation, abris, AME, sécurité alimentaire, protection, moyens de subsistance.",
    stats: {
      projects_completed: 15,
      people_helped: 1456686,
      partners_count: 8,
      experience_years: 27,
    },
    success_story: {
      title: "Distribution d'articles ménagers essentiels — Nyiragongo",
      organisation: "AIDES",
      period: "01 Octobre 2025 — 31 Décembre 2025",
      description:
        "La distribution directe des articles ménagers essentiels (AME), incluant des Kits d'Hygiène Menstruelle (KHM), a été réalisée au profit de 285 ménages retournés et communautés hôtes vulnérables, affectés par les conflits armés dans l'aire de santé de Buhumba, Zone de santé de Nyiragongo, Territoire de Nyiragongo, Province du Nord-Kivu, RDC.",
      results: {
        people_assisted: 2410,
        funding_obtained: "67,318 EUR",
        villages_covered: 4,
        households_reached: 285,
      },
      location: "Aire de santé de Buhumba, Zone de santé de Nyiragongo, Nord Kivu",
      sector: "Abris & AME",
      metric_display: "2,410 personnes assistées",
    },
    tags: [
      "Réfugiés",
      "Déplacés internes",
      "Humanitaire",
      "Protection",
      "AME",
      "CCCM",
    ],
  },
  {
    id: "org_003",
    name: "RACOJ",
    full_name: "Réseau des Associations Congolaises des Jeunes du Nord-Kivu",
    acronym: "RACOJ Nord-Kivu",
    logo_url: "/logos/racoj.png",
    founded: 2007,
    province_primary: "Nord Kivu",
    city: "Goma",
    verified: true,
    status: "active",
    provinces_covered: ["Nord Kivu", "Sud Kivu", "Kasaï Central"],
    sectors: [
      "Urgence",
      "Transition",
      "Développement",
      "Sécurité Alimentaire",
      "Abri/AME",
      "Nutrition",
      "Eau & Hygiène",
      "Assainissement",
      "Santé",
      "Protection",
      "Éducation",
    ],
    description_fr:
      "RACOJ Nord-Kivu a évolué au départ comme un mouvement des jeunes. L'organisation fut un cadre d'encadrement où les jeunes pouvaient mettre à profit leurs connaissances et ainsi acquérir l'expérience. Au fil du temps, l'organisation s'est construite une expertise et peut s'engager pour des projets de plus en plus complexes. RACOJ Nord-Kivu a gardé son assise communautaire en fondant ses actions sur la participation des jeunes.",
    mission_fr:
      "Regroupement des organisations des jeunes représentant toute la province du Nord-Kivu. Organisation des fora des jeunes sur diverses thématiques dont le VIH/SIDA, la santé sexuelle et reproductive et la consolidation de la paix. Développement de programmes d'encadrement des jeunes stagiaires en collaboration avec les établissements d'enseignement.",
    stats: {
      projects_completed: 18,
      people_helped: 65000,
      partners_count: 9,
    },
    tags: [
      "Jeunesse",
      "Nord Kivu",
      "Paix",
      "VIH/SIDA",
      "Santé reproductive",
      "Encadrement jeunes",
    ],
  },
  {
    id: "org_004",
    slug: "tpo",
    name: "TPO DRC",
    full_name: "Transcultural Psychosocial Organization",
    acronym: "TPO DRC",
    logo_url: "/logos/tpo.png",
    founded: 2015,
    province_primary: "Sud Kivu",
    city: "Bukavu",
    contact_email: "info@tpordc.org",
    verified: true,
    status: "active",
    provinces_covered: [
      "Nord Kivu",
      "Sud Kivu",
      "Maniema",
      "Tanganyika",
      "Kasaï Central",
      "Kasaï",
      "Tshopo",
      "Kinshasa",
      "Kwilu",
      "Mai-Ndombe",
      "Ituri",
      "Kwango",
      "Équateur",
    ],
    sectors: [
      "Protection",
      "WASH (Eau, Hygiène et Assainissement)",
      "Éducation",
      "Santé",
      "Nutrition",
      "Sécurité Alimentaire",
      "Agriculture",
      "Santé Sexuelle et Reproductive",
      "Urgence",
      "Environnement et Développement Durable",
      "Gouvernance et Paix",
    ],
    description_fr:
      "TPO DRC assiste les populations les plus vulnérables en situation particulièrement difficile (surtout les femmes et les enfants) y compris les victimes de conflits armés, des catastrophes naturelles et des épidémies dans 13 provinces de la RDC notamment, le Nord et Sud Kivu, Maniema, Tanganyika, Kasaï Central, Kasaï, Tshopo, Kinshasa, Kwilu, Mai-Ndombe, Ituri, Kwango et Équateur.",
    images: Array.from({ length: 17 }, (_, i) => `/images/tpo/tpo${i + 1}.png`),
    staff_count: 125,
    team_note: "Entre 100 et 150 membres",
    impact_note: "Plus de 200,000 personnes aidées à travers 132 projets réalisés.",
    stats: {
      projects_completed: 132,
      people_helped: 200000,
      partners_count: 12,
      staff_min: 100,
      staff_max: 150,
    },
    success_stories: [
      {
        id: "tpo_story_001",
        title: "Assistance alimentaire aux PDI du conflit M23 — Nord et Sud Kivu",
        organisation: "TPO DRC",
        period: "Juillet 2024 — Mars 2025",
        duration: "8 mois",
        description:
          "4,402 ménages de personnes déplacées internes (PDI) victimes du conflit armé de M23 dans le Nord-Kivu et Sud-Kivu bénéficient d'une assistance alimentaire à travers 3 distributions complètes grâce au financement USAID.",
        results: {
          people_assisted: 26412,
          households_reached: 4402,
          funding_obtained: "2,000,000 USD",
          funding_source: "USAID",
          distributions: 3,
          location: "Zone de santé, Province du Sud-Kivu",
        },
        sector: "Sécurité Alimentaire",
        metric_display: "26,412 personnes assistées · 2,000,000 USD",
      },
      {
        id: "tpo_story_002",
        title: "Distribution de kits AME et WASH aux ménages déplacés — Sud Kivu",
        organisation: "TPO DRC",
        period: "2022 — 2023",
        description:
          "19,000 ménages déplacés dans la province du Sud-Kivu sont assistés en kits AME (Articles Ménagers Essentiels) et WASH (Eau, Hygiène et Assainissement).",
        results: {
          people_assisted: 114000,
          households_reached: 19000,
          funding_obtained: "2,700,000 USD",
          provinces_covered: 1,
          location: "Province du Sud-Kivu",
        },
        sector: "Abris & AME / WASH",
        metric_display: "114,000 personnes assistées · 2,700,000 USD",
      },
      {
        id: "tpo_story_003",
        title: "Protection et prise en charge holistique — enfants et femmes affectés par les conflits",
        organisation: "TPO DRC",
        period: "2022 — 2025",
        description:
          "234,810 enfants et femmes affectés par les conflits armés dans le Sud-Kivu reçoivent une assistance en protection et prise en charge holistique.",
        results: {
          people_assisted: 234810,
          funding_obtained: "6,000,000 USD",
          provinces_covered: 1,
          location: "Province du Sud-Kivu",
          beneficiary_profile: "Enfants et femmes affectés par les conflits armés",
        },
        sector: "Protection",
        metric_display: "234,810 personnes assistées · 6,000,000 USD",
      },
    ],
    tags: [
      "Déplacés internes",
      "Conflits armés",
      "Femmes",
      "Enfants",
      "Protection",
      "WASH",
      "Sécurité alimentaire",
    ],
  },
  {
    id: "org_005",
    name: "SAD",
    full_name: "Santé et Développement",
    acronym: "SAD",
    logo_url: "/logos/sad.png",
    founded: 2014,
    province_primary: "Sud Kivu",
    city: "Bukavu",
    website: "https://sadrdc.org",
    verified: true,
    status: "active",
    provinces_covered: ["Sud Kivu", "Tanganyika", "Maniema", "Kinshasa"],
    territories_sud_kivu: [
      "Fizi (Mboko, Diné, Baraka, Uvira, Sange, Kigoma, Mwenga)",
      "Shabunda (Kigulube, Kabare, Kavumu, Kalehe, Kalonge, Bunyakiri, Bitale, Bulambika, Kambale)",
      "Walungu (Bwaangu, Nyangezi, Ruhuda, Ngomo, Ishamba)",
      "Ville de Bukavu (Kadutu, Ibanda, Bagira 2)",
    ],
    sectors: [
      "Urgences",
      "Santé",
      "Protection",
      "WASH",
      "Développement durable",
      "Environnement",
    ],
    description_fr:
      "Santé et Développement a été créé en 2014. Sa vision est : Un monde meilleur, épris de paix et de liberté, où la dignité et les droits des individus sont respectés, où la solidarité humaine conduit à la construction d'un monde meilleur.",
    mission_fr:
      "Restaurer la dignité et l'assistance humanitaire urgente aux hommes et aux femmes victimes des souffrances dues aux calamités naturelles et conflits armés avec un accent particulier aux femmes survivantes des viols et violences sexuelles et basées sur le genre, femmes marginalisées, aux jeunes et aux enfants en situation difficile. Participer au développement communautaire en promouvant l'auto prise en charge communautaire et la protection de l'environnement. Réduire la pauvreté et accroître le bien-être à travers les actions de développement durable des populations démunies.",
    stats: {
      projects_completed: 16,
      people_helped: 48000,
      partners_count: 7,
    },
    tags: [
      "SGBV",
      "Femmes",
      "Sud Kivu",
      "Développement durable",
      "Urgences",
      "Dignité humaine",
    ],
  },
];
