import type { Organisation } from "@/types/organization";

export const organizations: Organisation[] = [
  {
    id: "org_001",
    name: "ADSSE",
    full_name: "Association pour le Développement Social et la Sauvegarde de l'Environnement",
    acronym: "ADSSE",
    logo_url: "/logos/adsse.png",
    founded: 1997,
    founded_date: "15 mai 1997",
    founded_city: "Bukavu",
    founded_province: "Sud-Kivu",
    province_primary: "Ituri",
    city: "Bunia",
    headquarters: "Avenue du Bas-Congo No. 835, Commune de la Gombe, Kinshasa, RD Congo",
    website: "http://www.adsse.org",
    contact_email: "info@adsse.org",
    contact_email_1: "info@adsse.org",
    contact_email_2: "xmayele@adsse.org",
    contact_phone: "+243 815 117 685",
    verified: true,
    status: "active",
    experience_years: 27,
    experience_badge: "Plus de 27 ans d'expérience dans le travail communautaire.",
    provinces_covered: [
      "Ituri",
      "Nord Kivu",
      "Sud Kivu",
      "Kinshasa",
      "Maniema",
      "Tanganyika",
      "Haut-Katanga",
      "Kasaï Central",
      "Kasaï",
      "Haut-Uélé",
      "Nord-Ubangi",
      "Sud-Ubangi",
      "Haut-Lomami",
      "Équateur",
    ],
    sectors: [
      "Abris et Articles Ménagers Essentiels (AME)",
      "Livelihood (Moyens de subsistance)",
      "Nutrition",
      "Eau, Hygiène et Assainissement (EHA/WASH)",
      "Éducation",
    ],
    description: "Créée le 17 mai 1997 à Bukavu, dans la province du Sud-Kivu en République Démocratique du Congo, dans le contexte post-génocide rwandais, l'Association pour le Développement Social et la Sauvegarde de l'Environnement (ADSSE) est une organisation non gouvernementale (ONG) de droit congolais.",
    description_fr:
      "Créée le 17 mai 1997 à Bukavu, dans la province du Sud-Kivu en République Démocratique du Congo, dans le contexte post-génocide rwandais, l'Association pour le Développement Social et la Sauvegarde de l'Environnement (ADSSE) est une organisation non gouvernementale (ONG) de droit congolais.",
    vision: "Contribuer à l'action humanitaire localisée dans le respect de l'environnement, pour une plus grande efficacité et rapidité.",
    mission_fr:
      "Aider la population à identifier ses problèmes et les transformer en projets de développement. Initier des projets pour restaurer l'équilibre environnemental après des catastrophes naturelles ou des guerres. Créer des initiatives pour alléger la corvée des femmes et leur permettre de participer aux activités économiques. Soutenir les victimes de catastrophes naturelles, de violences sexuelles et les populations vulnérables.",
    mission_points: [
      "Aider la population à identifier ses problèmes et les transformer en projets de développement.",
      "Initier des projets pour restaurer l'équilibre environnemental après des catastrophes naturelles ou des guerres.",
      "Créer des initiatives pour alléger la corvée des femmes et leur permettre de participer aux activités économiques.",
      "Soutenir les victimes de catastrophes naturelles, de violences sexuelles et les populations vulnérables (réfugiés, déplacés internes, etc.).",
    ],
    domains: [
      "Activités humanitaires.",
      "Activités de développement : renforcer l'engagement et la résilience au sein de la communauté.",
      "Reboisement, lutte contre la déforestation et le changement climatique.",
    ],
    values: [
      "Prise en compte des 4 principes humanitaires dans les interventions",
      "Transparence & Redevabilité",
      "Protection de l'environnement",
      "Intégrité & lutte contre les abus sexuels",
    ],
    images: [
      "/images/adsse/adsse1.png",
      "/images/adsse/adsse2.png",
      "/images/adsse/adsse3.png",
      "/images/adsse/adsse4.png",
    ],
    map_image: "/images/adsse/adssemap.png",
    partner_logos: Array.from({ length: 11 }, (_, i) => `/images/adsse/partners/logo${i + 1}.png`),
    staff_count: 225,
    offices_count: 19,
    impact_note: "En 27 ans d'existence, ADSSE a assisté 12,780,000 personnes dont : 983,000 réfugiés (8%), 9,628,000 personnes déplacées internes (75%) et 2,169,000 communautés hôtes (17%)",
    team_note: "225 staffs répartis sur 19 bureaux à travers le pays",
    stats: {
      projects_completed: 47,
      people_helped: 12780000,
      partners_count: 11,
      experience_years: 27,
    },
    tags: [
      "Développement communautaire",
      "Protection environnement",
      "Femmes",
      "Réfugiés",
      "Déplacés internes",
    ],
  },
  {
    id: "org_002",
    slug: "aides",
    name: "AIDES",
    full_name: "Actions et Interventions pour le Développement et l'Encadrement Social",
    acronym: "AIDES",
    logo_url: "/logos/aides.png",
    founded: 1998,
    province_primary: "Nord Kivu",
    city: "Goma",
    headquarters: "Siège social à Kinshasa",
    headquarters_city: "Kinshasa",
    contact_email: "contact@aides-drc.org",
    social: {
      twitter: "https://x.com/aides_rdc?s=11",
      facebook: "https://m.facebook.com/aidesgom/",
    },
    verified: true,
    status: "active",
    provinces_covered: [
      "Kinshasa",
      "Nord Kivu",
      "Sud Kivu",
      "Tanganyika",
      "Kasaï",
      "Kasaï Central",
      "Nord Ubangi",
      "Sud Ubangi",
    ],
    operational_offices: [
      "Kinshasa (siège social)",
      "Goma (Nord Kivu)",
      "Beni (Nord Kivu)",
      "Bukavu (Sud Kivu)",
      "Uvira (Sud Kivu)",
      "Baraka (Sud Kivu)",
      "Kalemie (Tanganyika)",
      "Nyunzu (Tanganyika)",
      "Tshikapa (Kasaï)",
      "Kananga (Kasaï Central)",
      "Gbadolite (Nord Ubangi)",
      "Bili (Nord Ubangi)",
      "Yakoma (Nord Ubangi)",
      "Libenge (Sud Ubangi)",
      "Zongo (Sud Ubangi)",
    ],
    sectors: [
      "Protection",
      "Abris & Articles Ménagers Essentiels (AME)",
      "CCCM (Coordination et Gestion des Sites)",
      "Santé",
      "Sécurité Alimentaire",
      "Moyens de subsistance",
    ],
    description_fr:
      "AIDES est une organisation non gouvernementale de droit congolais qui apporte une assistance humanitaire intégrée, impartiale et digne aux victimes des crises humanitaires (réfugiés, personnes déplacées internes, retournés, rapatriés) et autres catastrophes (sinistrés) en répondant à leurs besoins essentiels, en protégeant leurs droits fondamentaux et en renforçant leur autonomie et leur résilience. Ses interventions se sont élargies au fil du temps sur le territoire national où les besoins se font sentir.",
    staff_count: 347,
    offices_count: 15,
    team_note: "347 membres, employés de AIDES de la Direction Générale et des différents projets",
    impact_note: "En 2025, environ 1,456,686 personnes sont assistées à travers 15 projets mis en œuvre dans les secteurs de santé, éducation, abris, AME, sécurité alimentaire, protection, moyens de subsistance.",
    stats: {
      projects_completed: 15,
      people_helped: 1456686,
      partners_count: 8,
      experience_years: 27,
    },
    success_story: {
      title: "Distribution d'articles ménagers essentiels — Nyiragongo",
      organisation: "AIDES",
      period: "01 Octobre 2025 — 31 Décembre 2025",
      description:
        "La distribution directe des articles ménagers essentiels (AME), incluant des Kits d'Hygiène Menstruelle (KHM), a été réalisée au profit de 285 ménages retournés et communautés hôtes vulnérables, affectés par les conflits armés dans l'aire de santé de Buhumba, Zone de santé de Nyiragongo, Territoire de Nyiragongo, Province du Nord-Kivu, RDC.",
      results: {
        people_assisted: 2410,
        funding_obtained: "67,318 EUR",
        villages_covered: 4,
        households_reached: 285,
      },
      location: "Aire de santé de Buhumba, Zone de santé de Nyiragongo, Nord Kivu",
      sector: "Abris & AME",
      metric_display: "2,410 personnes assistées",
    },
    tags: [
      "Réfugiés",
      "Déplacés internes",
      "Humanitaire",
      "Protection",
      "AME",
      "CCCM",
    ],
  },
  {
    id: "org_003",
    name: "RACOJ",
    full_name: "Réseau des Associations Congolaises des Jeunes du Nord-Kivu",
    acronym: "RACOJ Nord-Kivu",
    logo_url: "/logos/racoj.png",
    founded: 2007,
    province_primary: "Nord Kivu",
    city: "Goma",
    website: "https://racojnk.org/",
    verified: true,
    status: "active",
    provinces_covered: ["Nord Kivu", "Sud Kivu", "Kasaï Central"],
    sectors: [
      "Urgence",
      "Transition",
      "Développement",
      "Sécurité Alimentaire",
      "Abri/AME",
      "Nutrition",
      "Eau & Hygiène",
      "Assainissement",
      "Santé",
      "Protection",
      "Éducation",
    ],
    description_fr:
      "RACOJ Nord-Kivu a évolué au départ comme un mouvement des jeunes. L'organisation fut un cadre d'encadrement où les jeunes pouvaient mettre à profit leurs connaissances et ainsi acquérir l'expérience. Au fil du temps, l'organisation s'est construite une expertise et peut s'engager pour des projets de plus en plus complexes. RACOJ Nord-Kivu a gardé son assise communautaire en fondant ses actions sur la participation des jeunes.",
    mission_fr:
      "Regroupement des organisations des jeunes représentant toute la province du Nord-Kivu. Organisation des fora des jeunes sur diverses thématiques dont le VIH/SIDA, la santé sexuelle et reproductive et la consolidation de la paix. Développement de programmes d'encadrement des jeunes stagiaires en collaboration avec les établissements d'enseignement.",
    stats: {
      projects_completed: 18,
      people_helped: 65000,
      partners_count: 9,
    },
    tags: [
      "Jeunesse",
      "Nord Kivu",
      "Paix",
      "VIH/SIDA",
      "Santé reproductive",
      "Encadrement jeunes",
    ],
  },
  {
    id: "org_004",
    slug: "tpo",
    name: "TPO DRC",
    full_name: "Transcultural Psychosocial Organization",
    acronym: "TPO DRC",
    logo_url: "/logos/tpo.png",
    founded: 2015,
    province_primary: "Sud Kivu",
    city: "Bukavu",
    contact_email: "info@tpordc.org",
    website: "https://www.tpordc.org/",
    verified: true,
    status: "active",
    provinces_covered: [
      "Nord Kivu",
      "Sud Kivu",
      "Maniema",
      "Tanganyika",
      "Kasaï Central",
      "Kasaï",
      "Tshopo",
      "Kinshasa",
      "Kwilu",
      "Mai-Ndombe",
      "Ituri",
      "Kwango",
      "Équateur",
    ],
    sectors: [
      "Protection",
      "WASH (Eau, Hygiène et Assainissement)",
      "Éducation",
      "Santé",
      "Nutrition",
      "Sécurité Alimentaire",
      "Agriculture",
      "Santé Sexuelle et Reproductive",
      "Urgence",
      "Environnement et Développement Durable",
      "Gouvernance et Paix",
    ],
    description_fr:
      "TPO DRC assiste les populations les plus vulnérables en situation particulièrement difficile (surtout les femmes et les enfants) y compris les victimes de conflits armés, des catastrophes naturelles et des épidémies dans 13 provinces de la RDC notamment, le Nord et Sud Kivu, Maniema, Tanganyika, Kasaï Central, Kasaï, Tshopo, Kinshasa, Kwilu, Mai-Ndombe, Ituri, Kwango et Équateur.",
    images: Array.from({ length: 17 }, (_, i) => `/images/tpo/tpo${i + 1}.png`),
    staff_count: 125,
    team_note: "Entre 100 et 150 membres",
    impact_note: "Plus de 200,000 personnes aidées à travers 132 projets réalisés.",
    stats: {
      projects_completed: 132,
      people_helped: 200000,
      partners_count: 12,
      staff_min: 100,
      staff_max: 150,
    },
    success_stories: [
      {
        id: "tpo_story_001",
        title: "Assistance alimentaire aux PDI du conflit M23 — Nord et Sud Kivu",
        organisation: "TPO DRC",
        period: "Juillet 2024 — Mars 2025",
        duration: "8 mois",
        description:
          "4,402 ménages de personnes déplacées internes (PDI) victimes du conflit armé de M23 dans le Nord-Kivu et Sud-Kivu bénéficient d'une assistance alimentaire à travers 3 distributions complètes grâce au financement USAID.",
        results: {
          people_assisted: 26412,
          households_reached: 4402,
          funding_obtained: "2,000,000 USD",
          funding_source: "USAID",
          distributions: 3,
          location: "Zone de santé, Province du Sud-Kivu",
        },
        sector: "Sécurité Alimentaire",
        metric_display: "26,412 personnes assistées · 2,000,000 USD",
      },
      {
        id: "tpo_story_002",
        title: "Distribution de kits AME et WASH aux ménages déplacés — Sud Kivu",
        organisation: "TPO DRC",
        period: "2022 — 2023",
        description:
          "19,000 ménages déplacés dans la province du Sud-Kivu sont assistés en kits AME (Articles Ménagers Essentiels) et WASH (Eau, Hygiène et Assainissement).",
        results: {
          people_assisted: 114000,
          households_reached: 19000,
          funding_obtained: "2,700,000 USD",
          provinces_covered: 1,
          location: "Province du Sud-Kivu",
        },
        sector: "Abris & AME / WASH",
        metric_display: "114,000 personnes assistées · 2,700,000 USD",
      },
      {
        id: "tpo_story_003",
        title: "Protection et prise en charge holistique — enfants et femmes affectés par les conflits",
        organisation: "TPO DRC",
        period: "2022 — 2025",
        description:
          "234,810 enfants et femmes affectés par les conflits armés dans le Sud-Kivu reçoivent une assistance en protection et prise en charge holistique.",
        results: {
          people_assisted: 234810,
          funding_obtained: "6,000,000 USD",
          provinces_covered: 1,
          location: "Province du Sud-Kivu",
          beneficiary_profile: "Enfants et femmes affectés par les conflits armés",
        },
        sector: "Protection",
        metric_display: "234,810 personnes assistées · 6,000,000 USD",
      },
    ],
    tags: [
      "Déplacés internes",
      "Conflits armés",
      "Femmes",
      "Enfants",
      "Protection",
      "WASH",
      "Sécurité alimentaire",
    ],
  },
  {
    id: "org_006",
    slug: "encore",
    name: "ENCORE",
    full_name: "Ensemble pour des Communautés Résilientes",
    acronym: "ENCORE",
    logo_url: "/logos/encore.png",
    founded: 2023,
    province_primary: "Ituri",
    city: "Bunia",
    headquarters: "No. 1437, Avenue de l'OUA, Quartier Yambi Yaya, Commune Mbunya, Bunia, Ituri, RD Congo",
    contact_email: "encorerdc24@gmail.com",
    contact_email_1: "encorerdc24@gmail.com",
    contact_email_2: "direction@encoredrc.org",
    website: "https://encoredrc.org/",
    contact_phone: "+243 894 969 611",
    social: {
      facebook: "https://www.facebook.com/share/17Q8XPPNPC/",
      twitter: "https://x.com/encorerdc",
    },
    verified: true,
    status: "active",
    provinces_covered: ["Ituri"],
    sectors: [
      "Protection — Violences Basées sur le Genre (VBG)",
      "Santé et Nutrition",
      "Éducation",
      "WASH (Eau, Hygiène et Assainissement)",
      "Cohésion sociale",
      "Autonomisation des femmes",
    ],
    description_fr:
      "ENCORE œuvre pour renforcer la résilience des communautés affectées par les crises humanitaires. Elle intervient principalement dans les domaines de la santé, de la protection, en particulier la lutte contre les violences basées sur le genre (VBG), ainsi que la cohésion sociale et l'autonomisation des femmes. L'organisation sert des populations vulnérables, notamment les personnes déplacées internes, les femmes survivantes de VBG, les enfants et les communautés hôtes, avec des interventions concentrées principalement dans la province de l'Ituri, autour de Bunia et ses zones de santé environnantes.",
    images: Array.from({ length: 22 }, (_, i) => `/images/encore/encore${i + 1}.png`),
    staff_count: 12,
    team_note: "Entre 10 et 15 membres",
    impact_note: "15,000 personnes aidées depuis la création de l'organisation en 2023.",
    stats: {
      projects_completed: 8,
      people_helped: 15000,
      partners_count: 4,
      staff_min: 10,
      staff_max: 15,
    },
    success_stories: [
      {
        id: "encore_story_001",
        title: "Cliniques mobiles de santé — Biringi et Nyarambe",
        organisation: "ENCORE",
        period: "Mars 2026",
        description:
          "ENCORE a organisé des cliniques mobiles dans les zones de santé de Biringi et Nyarambe afin d'améliorer l'accès aux services de santé pour les communautés vivant dans des zones enclavées. Ces interventions ont permis d'offrir des consultations en santé sexuelle et reproductive, des sensibilisations sur les IST/VIH ainsi que des services prénatals.",
        results: {
          people_assisted: 600,
          zones_covered: 2,
          location: "Zones de santé de Biringi et Nyarambe, Ituri",
        },
        sector: "Santé",
        metric_display: "600+ personnes sensibilisées · 300+ consultations réalisées",
      },
      {
        id: "encore_story_002",
        title: "Prise en charge holistique des survivantes de VBG",
        organisation: "ENCORE",
        period: "Novembre 2025",
        description:
          "ENCORE a mis en œuvre des activités de prise en charge holistique des survivantes de violences basées sur le genre (VBG), incluant l'accompagnement médical, le soutien psychosocial et l'orientation vers des services juridiques. En parallèle, des actions de sensibilisation communautaire ont été menées pour prévenir les VBG et encourager le recours aux services disponibles.",
        results: {
          people_assisted: 200,
          beneficiary_profile: "Femmes survivantes de VBG — accompagnement médical, psychosocial et juridique",
        },
        sector: "Protection — VBG",
        metric_display: "200+ survivantes accompagnées · 1,000+ personnes sensibilisées",
      },
      {
        id: "encore_story_003",
        title: "Campagnes de sensibilisation VBG — théâtre participatif et écoles",
        organisation: "ENCORE",
        period: "Octobre 2025 — Janvier 2026",
        description:
          "ENCORE a organisé des campagnes de sensibilisation communautaire à travers des pièces de théâtre participatives et des séances dans les écoles, visant à promouvoir la prévention des violences basées sur le genre (VBG), les droits des femmes et les bonnes pratiques de santé. Ces activités ont favorisé le dialogue communautaire et le changement de comportements.",
        results: {
          people_assisted: 1500,
          location: "Villages et écoles des zones d'intervention, Ituri",
        },
        sector: "Protection — VBG",
        metric_display: "1,500+ personnes sensibilisées dans villages et écoles",
      },
    ],
    tags: [
      "Protection",
      "VBG",
      "Santé",
      "Femmes",
      "Ituri",
      "Cohésion sociale",
      "Autonomisation des femmes",
    ],
  },
  {
    id: "org_007",
    slug: "rpdi",
    name: "RPDI",
    full_name: "Rassemblement des Personnes Handicapées pour le Développement Intégral",
    acronym: "RPDI-ASBL",
    logo_url: "/logos/rpdi.png",
    founded: 2019,
    province_primary: "Ituri",
    city: "Bunia",
    headquarters: "Boulevard de Libération, en face de l'ISTM Nyakunde, Quartier Yambi Yaya, Commune Mbunya, Bunia, Ituri, RD Congo",
    contact_email: "rpdicongo@gmail.com",
    contact_email_1: "rpdicongo@gmail.com",
    contact_phone: "+243 999 421 214",
    verified: true,
    status: "active",
    provinces_covered: ["Ituri", "Nord Kivu"],
    sectors: [
      "Protection",
      "WASH (Eau, Hygiène et Assainissement)",
      "Éducation",
      "Santé",
      "Sécurité Alimentaire",
      "Formation professionnelle",
      "Accompagnement des Peuples Autochtones",
      "Inclusion des personnes handicapées",
      "Moyens de subsistance",
    ],
    description_fr:
      "Défense des droits des personnes vivant avec handicap et autres personnes vulnérables (PVH-APV). RPDI œuvre pour l'inclusion sociale et économique des populations les plus marginalisées, notamment les personnes handicapées, les déplacés internes et les peuples autochtones, dans les provinces de l'Ituri et du Nord-Kivu.",
    images: Array.from({ length: 7 }, (_, i) => `/images/rpdi/rpdi${i + 1}.png`),
    staff_count: 47,
    team_note: "47 membres",
    impact_note: "Amélioration de l'inclusion sociale et économique des personnes handicapées et déplacées à Bunia et Beni.",
    stats: {
      projects_completed: 6,
      people_helped: 5000,
      partners_count: 3,
      staff_min: 47,
      staff_max: 47,
    },
    success_stories: [
      {
        id: "rpdi_story_001",
        title: "Renforcement institutionnel par le programme ToGETHER",
        organisation: "RPDI",
        period: "2025",
        description:
          "Suite à une évaluation approfondie de ses capacités organisationnelles par le programme ToGETHER, RPDI a entrepris un processus structuré de renforcement institutionnel ayant conduit à des améliorations significatives en gouvernance. L'organisation dispose désormais de systèmes formalisés, d'un personnel qualifié et d'outils de gestion alignés aux standards CHS. Ces avancées ont permis d'accroître la crédibilité de RPDI, de renforcer la confiance des partenaires et d'améliorer l'impact des interventions auprès des populations vulnérables.",
        results: {
          people_assisted: 5000,
          location: "Ituri, RD Congo",
          beneficiary_profile:
            "Transformation d'une structure communautaire émergente en acteur humanitaire crédible, aligné aux standards CHS (Core Humanitarian Standards), capable de gérer des financements et de produire des résultats mesurables.",
        },
        sector: "Gouvernance & Renforcement des capacités",
        metric_display: "Alignement aux standards CHS · Gouvernance renforcée · Impact ToGETHER",
      },
      {
        id: "rpdi_story_002",
        title: "Création d'un espace vert à l'Université de Bunia",
        organisation: "RPDI",
        period: "2024 — 2025",
        description:
          "Le projet de création d'un espace vert à l'Université de Bunia a permis d'améliorer significativement le cadre d'apprentissage et le bien-être des étudiants, tout en renforçant la sensibilisation environnementale et la cohésion sociale. Grâce à la plantation d'arbres, à l'aménagement d'espaces de détente et à l'implication active des étudiants, le campus bénéficie désormais d'un environnement plus sain, durable et attractif.",
        results: {
          people_assisted: 500,
          location: "Université de Bunia, Ituri",
          beneficiary_profile:
            "Transformation d'un espace dégradé en laboratoire écologique et social — modèle reproductible d'intégration du développement durable en milieu universitaire.",
        },
        sector: "Environnement & Éducation",
        metric_display: "Campus transformé · Modèle de développement durable",
      },
      {
        id: "rpdi_story_003",
        title: "Inclusion sociale et économique des personnes handicapées et déplacées — Bunia et Beni",
        organisation: "RPDI",
        period: "2024 — 2025",
        description:
          "Le projet a permis d'améliorer significativement l'inclusion sociale et économique des personnes handicapées et déplacées vulnérables à Bunia et Beni. Grâce à des activités de renforcement des capacités, d'appui aux moyens de subsistance et de sensibilisation communautaire, les bénéficiaires ont accru leurs revenus, renforcé leur participation sociale et amélioré leur accès aux services essentiels. Le projet a contribué à réduire la stigmatisation, renforcer la résilience des ménages et promouvoir une inclusion durable.",
        results: {
          people_assisted: 5000,
          provinces_covered: 2,
          location: "Bunia (Ituri) et Beni (Nord Kivu)",
          beneficiary_profile:
            "Personnes handicapées et déplacées — transformation de la vulnérabilité en opportunité économique et sociale.",
        },
        sector: "Protection & Inclusion",
        metric_display: "Inclusion économique · Bunia et Beni",
      },
    ],
    tags: [
      "Handicap",
      "Inclusion",
      "Peuples autochtones",
      "Déplacés internes",
      "Ituri",
      "Nord Kivu",
      "Droits humains",
    ],
  },
  {
    id: "org_005",
    name: "SAD",
    full_name: "Santé et Développement",
    acronym: "SAD",
    logo_url: "/logos/sad.png",
    founded: 2014,
    province_primary: "Sud Kivu",
    city: "Bukavu",
    website: "https://sadrdc.org",
    verified: true,
    status: "active",
    provinces_covered: ["Sud Kivu", "Tanganyika", "Maniema", "Kinshasa"],
    territories_sud_kivu: [
      "Fizi (Mboko, Diné, Baraka, Uvira, Sange, Kigoma, Mwenga)",
      "Shabunda (Kigulube, Kabare, Kavumu, Kalehe, Kalonge, Bunyakiri, Bitale, Bulambika, Kambale)",
      "Walungu (Bwaangu, Nyangezi, Ruhuda, Ngomo, Ishamba)",
      "Ville de Bukavu (Kadutu, Ibanda, Bagira 2)",
    ],
    sectors: [
      "Urgences",
      "Santé",
      "Protection",
      "WASH",
      "Développement durable",
      "Environnement",
    ],
    description_fr:
      "Santé et Développement a été créé en 2014. Sa vision est : Un monde meilleur, épris de paix et de liberté, où la dignité et les droits des individus sont respectés, où la solidarité humaine conduit à la construction d'un monde meilleur.",
    mission_fr:
      "Restaurer la dignité et l'assistance humanitaire urgente aux hommes et aux femmes victimes des souffrances dues aux calamités naturelles et conflits armés avec un accent particulier aux femmes survivantes des viols et violences sexuelles et basées sur le genre, femmes marginalisées, aux jeunes et aux enfants en situation difficile. Participer au développement communautaire en promouvant l'auto prise en charge communautaire et la protection de l'environnement. Réduire la pauvreté et accroître le bien-être à travers les actions de développement durable des populations démunies.",
    stats: {
      projects_completed: 16,
      people_helped: 48000,
      partners_count: 7,
    },
    tags: [
      "SGBV",
      "Femmes",
      "Sud Kivu",
      "Développement durable",
      "Urgences",
      "Dignité humaine",
    ],
  },
];
