import type { Organisation } from "@/types/organization";

export const organizations: Organisation[] = [
  {
    id: "org_001",
    name: "ADSSE",
    full_name: "Association pour le Développement Social et la Sauvegarde de l'Environnement",
    acronym: "ADSSE",
    logo_url: "/logos/adsse.png",
    founded: 1997,
    founded_date: "15 mai 1997",
    founded_city: "Bukavu",
    founded_province: "Sud-Kivu",
    province_primary: "Ituri",
    city: "Bunia",
    headquarters: "Avenue du Bas-Congo No. 835, Commune de la Gombe, Kinshasa, RD Congo",
    website: "http://www.adsse.org",
    contact_email: "info@adsse.org",
    contact_email_1: "info@adsse.org",
    contact_email_2: "xmayele@adsse.org",
    contact_phone: "+243 815 117 685",
    verified: true,
    status: "active",
    experience_years: 27,
    experience_badge: "Plus de 27 ans d'expérience dans le travail communautaire.",
    provinces_covered: [
      "Ituri",
      "Nord Kivu",
      "Sud Kivu",
      "Kinshasa",
      "Maniema",
      "Tanganyika",
      "Haut-Katanga",
      "Kasaï Central",
      "Kasaï",
      "Haut-Uélé",
      "Nord-Ubangi",
      "Sud-Ubangi",
      "Haut-Lomami",
      "Équateur",
    ],
    sectors: [
      "Abris et Articles Ménagers Essentiels (AME)",
      "Livelihood (Moyens de subsistance)",
      "Nutrition",
      "Eau, Hygiène et Assainissement (EHA/WASH)",
      "Éducation",
    ],
    description: "Créée le 17 mai 1997 à Bukavu, dans la province du Sud-Kivu en République Démocratique du Congo, dans le contexte post-génocide rwandais, l'Association pour le Développement Social et la Sauvegarde de l'Environnement (ADSSE) est une organisation non gouvernementale (ONG) de droit congolais.",
    description_fr:
      "Créée le 17 mai 1997 à Bukavu, dans la province du Sud-Kivu en République Démocratique du Congo, dans le contexte post-génocide rwandais, l'Association pour le Développement Social et la Sauvegarde de l'Environnement (ADSSE) est une organisation non gouvernementale (ONG) de droit congolais.",
    vision: "Contribuer à l'action humanitaire localisée dans le respect de l'environnement, pour une plus grande efficacité et rapidité.",
    mission_fr:
      "Aider la population à identifier ses problèmes et les transformer en projets de développement. Initier des projets pour restaurer l'équilibre environnemental après des catastrophes naturelles ou des guerres. Créer des initiatives pour alléger la corvée des femmes et leur permettre de participer aux activités économiques. Soutenir les victimes de catastrophes naturelles, de violences sexuelles et les populations vulnérables.",
    mission_points: [
      "Aider la population à identifier ses problèmes et les transformer en projets de développement.",
      "Initier des projets pour restaurer l'équilibre environnemental après des catastrophes naturelles ou des guerres.",
      "Créer des initiatives pour alléger la corvée des femmes et leur permettre de participer aux activités économiques.",
      "Soutenir les victimes de catastrophes naturelles, de violences sexuelles et les populations vulnérables (réfugiés, déplacés internes, etc.).",
    ],
    domains: [
      "Activités humanitaires.",
      "Activités de développement : renforcer l'engagement et la résilience au sein de la communauté.",
      "Reboisement, lutte contre la déforestation et le changement climatique.",
    ],
    values: [
      "Prise en compte des 4 principes humanitaires dans les interventions",
      "Transparence & Redevabilité",
      "Protection de l'environnement",
      "Intégrité & lutte contre les abus sexuels",
    ],
    images: [
      "/images/adsse/adsse1.png",
      "/images/adsse/adsse2.png",
      "/images/adsse/adsse3.png",
      "/images/adsse/adsse4.png",
    ],
    map_image: "/images/adsse/adssemap.png",
    partner_logos: Array.from({ length: 11 }, (_, i) => `/images/adsse/partners/logo${i + 1}.png`),
    staff_count: 225,
    offices_count: 19,
    impact_note: "En 27 ans d'existence, ADSSE a assisté 12,780,000 personnes dont : 983,000 réfugiés (8%), 9,628,000 personnes déplacées internes (75%) et 2,169,000 communautés hôtes (17%)",
    team_note: "225 staffs répartis sur 19 bureaux à travers le pays",
    stats: {
      projects_completed: 47,
      people_helped: 12780000,
      partners_count: 11,
      experience_years: 27,
    },
    tags: [
      "Développement communautaire",
      "Protection environnement",
      "Femmes",
      "Réfugiés",
      "Déplacés internes",
    ],
  },
  {
    id: "org_002",
    name: "AIDES",
    full_name: "Actions et Interventions pour le Développement et l'Encadrement Social",
    acronym: "AIDES",
    logo_url: "/logos/aides.png",
    founded: 2005,
    province_primary: "Nord Kivu",
    city: "Goma",
    social: {
      twitter: "https://x.com/aides_rdc?s=11",
      facebook: "https://m.facebook.com/aidesgom/",
    },
    verified: true,
    status: "active",
    provinces_covered: ["Nord Kivu", "Sud Kivu", "Ituri"],
    sectors: [
      "AME/Abri",
      "Éducation",
      "Sécurité Alimentaire",
      "Santé",
      "Protection",
      "EHA",
      "Nutrition",
      "Assistance aux Réfugiés",
      "CCCM",
    ],
    description_fr:
      "Créée dans le but de venir en aide aux personnes en détresse, AIDES a commencé à travailler dans le cadre d'assistance aux réfugiés avant d'étendre ses activités à toutes les personnes affectées par les calamités et les conflits notamment à l'Est de la RDC. Grâce à ses relations efficaces avec ses partenaires, elle aide à mettre fin aux inégalités, à encourager la justice et à maintenir la dignité.",
    mission_fr:
      "Les programmes d'aide humanitaire mis en œuvre favorisent la dignité de toute personne, indépendamment des croyances religieuses, politiques ou culturelles.",
    stats: {
      projects_completed: 31,
      people_helped: 120000,
      partners_count: 18,
    },
    tags: [
      "Réfugiés",
      "Conflits armés",
      "Humanitaire",
      "Est RDC",
      "Dignité humaine",
    ],
  },
  {
    id: "org_003",
    name: "RACOJ",
    full_name: "Réseau des Associations Congolaises des Jeunes du Nord-Kivu",
    acronym: "RACOJ Nord-Kivu",
    logo_url: "/logos/racoj.png",
    founded: 2007,
    province_primary: "Nord Kivu",
    city: "Goma",
    verified: true,
    status: "active",
    provinces_covered: ["Nord Kivu", "Sud Kivu", "Kasaï Central"],
    sectors: [
      "Urgence",
      "Transition",
      "Développement",
      "Sécurité Alimentaire",
      "Abri/AME",
      "Nutrition",
      "Eau & Hygiène",
      "Assainissement",
      "Santé",
      "Protection",
      "Éducation",
    ],
    description_fr:
      "RACOJ Nord-Kivu a évolué au départ comme un mouvement des jeunes. L'organisation fut un cadre d'encadrement où les jeunes pouvaient mettre à profit leurs connaissances et ainsi acquérir l'expérience. Au fil du temps, l'organisation s'est construite une expertise et peut s'engager pour des projets de plus en plus complexes. RACOJ Nord-Kivu a gardé son assise communautaire en fondant ses actions sur la participation des jeunes.",
    mission_fr:
      "Regroupement des organisations des jeunes représentant toute la province du Nord-Kivu. Organisation des fora des jeunes sur diverses thématiques dont le VIH/SIDA, la santé sexuelle et reproductive et la consolidation de la paix. Développement de programmes d'encadrement des jeunes stagiaires en collaboration avec les établissements d'enseignement.",
    stats: {
      projects_completed: 18,
      people_helped: 65000,
      partners_count: 9,
    },
    tags: [
      "Jeunesse",
      "Nord Kivu",
      "Paix",
      "VIH/SIDA",
      "Santé reproductive",
      "Encadrement jeunes",
    ],
  },
  {
    id: "org_004",
    name: "TPO",
    full_name: "Transcultural Psychosocial Organization",
    acronym: "TPO RD Congo",
    logo_url: "/logos/tpo.png",
    founded: 2000,
    province_primary: "Sud Kivu",
    city: "Bukavu",
    headquarters: "Bukavu (siège social et administratif)",
    verified: true,
    status: "active",
    provinces_covered: [
      "Sud Kivu",
      "Nord Kivu",
      "Maniema",
      "Tanganyika",
      "Kasaï Central",
      "Kwango",
      "Kinshasa",
    ],
    sectors: [
      "Santé mentale & PSS",
      "SGBV",
      "Protection de l'enfant",
      "Éducation",
      "Gouvernance & Paix",
      "Transformation des conflits",
      "Santé",
      "Nutrition",
      "WASH",
      "Sécurité Alimentaire",
      "Environnement",
      "Développement durable",
    ],
    description_fr:
      "A propos de TPO: Mission — Appuyer les communautés vulnérables, les structures étatiques et celles de la société civile surtout en conflit et post-conflit à travers la promotion des interventions appropriées d'urgence, de relèvement précoce et de développement.",
    mission_fr:
      "Vision — Voir les bénéficiaires de nos actions devenir acteurs principaux de leur propre développement et de celui des autres pour un avenir merveilleux. Ces bénéficiaires sont en priorité les enfants ou les jeunes et les femmes. TPO collabore avec les organisations à base communautaire (OBC) identifiées dans la communauté, qui sont comptées actuellement à 54 à travers le pays.",
    stats: {
      projects_completed: 42,
      people_helped: 250000,
      partners_count: 28,
    },
    tags: [
      "Psychosocial",
      "Santé mentale",
      "Post-conflit",
      "Femmes",
      "Enfants",
      "OBC",
      "Transculturel",
    ],
  },
  {
    id: "org_005",
    name: "SAD",
    full_name: "Santé et Développement",
    acronym: "SAD",
    logo_url: "/logos/sad.png",
    founded: 2014,
    province_primary: "Sud Kivu",
    city: "Bukavu",
    website: "https://sadrdc.org",
    verified: true,
    status: "active",
    provinces_covered: ["Sud Kivu", "Tanganyika", "Maniema", "Kinshasa"],
    territories_sud_kivu: [
      "Fizi (Mboko, Diné, Baraka, Uvira, Sange, Kigoma, Mwenga)",
      "Shabunda (Kigulube, Kabare, Kavumu, Kalehe, Kalonge, Bunyakiri, Bitale, Bulambika, Kambale)",
      "Walungu (Bwaangu, Nyangezi, Ruhuda, Ngomo, Ishamba)",
      "Ville de Bukavu (Kadutu, Ibanda, Bagira 2)",
    ],
    sectors: [
      "Urgences",
      "Santé",
      "Protection",
      "WASH",
      "Développement durable",
      "Environnement",
    ],
    description_fr:
      "Santé et Développement a été créé en 2014. Sa vision est : Un monde meilleur, épris de paix et de liberté, où la dignité et les droits des individus sont respectés, où la solidarité humaine conduit à la construction d'un monde meilleur.",
    mission_fr:
      "Restaurer la dignité et l'assistance humanitaire urgente aux hommes et aux femmes victimes des souffrances dues aux calamités naturelles et conflits armés avec un accent particulier aux femmes survivantes des viols et violences sexuelles et basées sur le genre, femmes marginalisées, aux jeunes et aux enfants en situation difficile. Participer au développement communautaire en promouvant l'auto prise en charge communautaire et la protection de l'environnement. Réduire la pauvreté et accroître le bien-être à travers les actions de développement durable des populations démunies.",
    stats: {
      projects_completed: 16,
      people_helped: 48000,
      partners_count: 7,
    },
    tags: [
      "SGBV",
      "Femmes",
      "Sud Kivu",
      "Développement durable",
      "Urgences",
      "Dignité humaine",
    ],
  },
];
